name: garbage_scheduler_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0<3.0.0"


dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0

  provider: ^6.1.2


  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  
  
    
  http: ^1.2.2

  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.10

  shared_preferences: ^2.5.2
  flutter_feather_icons: ^2.0.0+1
 
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

  assets:
    - assets/welcome.gif
    - assets/splash.jpg
    - assets/lottie/login.json
    - assets/lottie/welcome.json
    - assets/lottie/su.json
    - assets/lottie/recycling.json
    - assets/lottie/schedule.json
    - assets/lottie/status.json
    - assets/login1.webp
    - assets/profile.png
    - assets/paper.jpg
    - assets/plastic.jpg
    - assets/metal.jpg
    - assets/glass.jpg
    - assets/dino.jpg
    - assets/cactus.png


 
